name: kpostal
description: Kpostal package can search for Korean postal addresses using Kakao postcode service.
version: 1.1.0
homepage: https://github.com/tykann/kpostal

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  assets:
    - assets/kakao_postcode_localhost.html
